# -*- coding: utf-8 -*-
"""Untitled3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1qUHjcFJaGUqRSfKzxECZHNhDjbnNr8qf
"""

def firstfunction():
  print("hello this is my first function")
firstfunction()



def argument(name):
  print(name + " is good")
argument("hiba")

def secfunction(fname,lname):
  print(fname + lname + " is good")
secfunction("Hiba","pt")

def myfunction(*names):
  print(" the good person " +names[3])
myfunction("sana","hiba","sahla","SHS")

def thirdfunc(child1,child2,child3):
  print("the eldest child is" + child2 )
thirdfunc("anu","manu","sanu")

def fifthfunc(**kid):
  print("the youngest child is" + kid["child3"])
fifthfunc(child1="anu",child2="manu",child3="arun")

def palindrom():
  n=input("enter word:")
  if n==n[::-1]:
    print("palindrom")
  else:
    print("not palindrom")
palindrom()

def prime():
  a=int(input("enter a number"))
  for i in range(2,a):
    if i%a==0:
      print(" is not prime")
      break
    else:
      print("is prime")
prime()